M48
; DRILL file {KiCad 7.0.3} date Mon 05 Jun 2023 08:38:01 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-05T20:38:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X5.0713Y-3.5531
X5.0831Y-4.5453
T2
X4.0551Y-2.874
X4.0551Y-5.2362
X7.1654Y-2.874
X7.1654Y-5.2362
T0
M30
