M48
; DRILL file {KiCad (6.0.11)} date Mon 27 Feb 2023 01:11:44 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-27T13:11:44-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X5.0713Y-3.5531
X5.0831Y-4.5453
T2
X4.0551Y-2.874
X4.0551Y-5.2362
X7.1654Y-2.874
X7.1654Y-5.2362
T0
M30
