M48
; DRILL file {KiCad 7.0.2} date Mon Oct 23 14:03:05 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-23T14:03:05-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X128.81Y-90.25
X129.11Y-115.45
T2
X103.0Y-73.0
X103.0Y-133.0
X182.0Y-73.0
X182.0Y-133.0
T0
M30
